### ISSUE TITLE
how to make aggregation work?

### ISSUE THREAD

**Issue by weswitt** [matthewwall/weewx-mqtt#10]
how do i get aggregation to generate both aggregate and individual ?? 

if i set the option to "aggregation = aggregate, individual" then i get an exception:

Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: MQTT: Unexpected exception of type <class 'AttributeError'>
Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: *** Traceback (most recent call last):
Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: ***   File "/home/weewx/bin/weewx/restx.py", line 378, in run_loop
Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: ***     self.process_record(_record, dbmanager)
Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: ***   File "/home/weewx/bin/user/mqtt.py", line 496, in process_record
Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: ***     if self.aggregation.find('aggregate') >= 0:
Jul  8 16:01:09 weathertest weewx[18648] ERROR weewx.restx: *** AttributeError: 'list' object has no attribute 'find'
Jul  8 16:01:09 weathertest weewx[18648] CRITICAL weewx.restx: MQTT: Thread terminating. Reason: 'list' object has no attribute 'find'

if i set the option to "aggregation = both" then all i get is individual.

**Comment by weswitt** [comment]
after reading the code i found that aggregation value is not treated as a list, but rather a string. putting quotes around the value fixed the problem.
