### ISSUE TITLE
update to README for weewx version > 5.0.0

### ISSUE THREAD

**Issue by mkullman** [matthewwall/weewx-mqtt#44]
"wee_extension --install weewx-mqtt.zip" no longer works with version 5.0.0 or higher
 use "weectl extension install weewx-mqtt.zip" instead

**Comment by PA8E** [comment]
I get: 

$ weectl extension install weewx-mqtt.zip
Using configuration file /etc/weewx/weewx.conf
Install extension 'weewx-mqtt.zip' (y/n)? y
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 75, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 67, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 90, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 132, in install_extension
    raise InstallError(f"Path {extension_path} does not exist.")
weecfg.extension.InstallError: Path weewx-mqtt.zip does not exist.
